import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import './globals.css';

import { Providers } from '@/store/providers';
import BaseHeader from '@/components/molecules/BaseHeader';
import BaseFooter from '@/components/molecules/BaseFooter';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-gray-50 ${inter.className} antialiased`}>
        <Providers>
          <BaseHeader />
          <div className="max-w-screen-xl px-4 mx-auto sm:px-0">{children}</div>
          <BaseFooter />
        </Providers>
      </body>
    </html>
  );
}
